import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithStrictChildren) {
  return (
    <html lang='en'>
      <body className='flex w-screen justify-center h-screen bg-gray-800'>
        <main className='w-full max-w-[420px] relative bg-white px-6 h-full'>{children}</main>
      </body>
    </html>
  );
}
